// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


namespace Dotnet_Homework
{

    [TestFixture]
    public class MyTests : BasePage
    {

        HomePage home;

        [SetUp]
        public void SetUp()
        {
            Initialize();
            home = new HomePage(driver);
        }

        [Test]
        public void aproductTest()
        {
            string assertText = home.AddToBasket();
            Thread.Sleep(2000);
            Assert.AreEqual("Sepete Git", assertText);
        }

        [Test]
        public void bbasketTest()
        {
            aproductTest();
            home.BasketControl();
        }
        
        [Test]
        public void cpasswordResetTest()
        {
            home.forgottenPasswordReset("sepetic41@gmail.com");
        }

        [TearDown]
        protected void Close()
        {
            TearDown();
        }

    }

}