// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.PageObjects;


namespace Dotnet_Homework
{

    public class HomePage : BasePage
    {

        public HomePage(IWebDriver driver)
        {
            HomePage.driver = driver;
            PageFactory.InitElements(driver, this);
        }
        [FindsBy(How = How.Id, Using = "searchData")]
        private IWebElement searchData;

        [FindsBy(How = How.CssSelector, Using = ".searchBtn")]
        private IWebElement searchButton;

        [FindsBy(How = How.CssSelector, Using = "#p-422486329 .lazy")]
        private IWebElement product;

        [FindsBy(How = How.LinkText, Using = "Sepete Ekle")]
        private IWebElement basket;

        [FindsBy(How = How.LinkText, Using = "Sepete Git")]
        private IWebElement goBasket;

        public String AddToBasket()
        {
            searchData.Click();
            searchData.SendKeys("sabun");
            searchButton.Click();
            product.Click();
            WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(8));
            wait.Until(driver => basket.Displayed);
            Assert.That(basket.Text, Is.EqualTo("Sepete Ekle"));
            driver.FindElement(By.CssSelector(".btnAddBasket")).Click();
            Thread.Sleep(2000);
            string assertText = goBasket.GetAttribute("title");

            return assertText;
        }

        [FindsBy(How = How.LinkText, Using = "Giriş Yap")]
        private IWebElement loginButton;

        [FindsBy(How = How.Id, Using = "forgotPassword")]
        private IWebElement forgotPassword;

        [FindsBy(How = How.Id, Using = "forgottenUserEmail")]
        private IWebElement forgottenUserEmail;

        [FindsBy(How = How.Id, Using = "sendLinkForPasswordBtn")]
        private IWebElement sendLinkForPasswordBtn;

        public void forgottenPasswordReset(string fUserEmail)
        {
            driver.Navigate().GoToUrl("https://www.n11.com/");
            Thread.Sleep(8000);
            loginButton.Click();
            Thread.Sleep(8000);
            forgotPassword.Click();
            Thread.Sleep(8000);
            WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(8));
            wait.Until(driver => sendLinkForPasswordBtn.Displayed);
            Assert.That(sendLinkForPasswordBtn.Text, Is.EqualTo("Gönder"));
            forgottenUserEmail.Click();
            forgottenUserEmail.SendKeys(fUserEmail);
            sendLinkForPasswordBtn.Click();
            Thread.Sleep(8000);
        }

        public void BasketControl()
        {
            Thread.Sleep(3000);
            driver.Navigate().GoToUrl("https://www.n11.com/");
            driver.FindElement(By.CssSelector(".myBasket")).Click();
            WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(8));
            wait.Until(driver => driver.FindElement(By.Id("js-buyBtn")).Displayed);

        }

    }
}